### ISSUE TITLE
Schedule Local Notification crashes application when user turns off Alarm

### ISSUE THREAD

**Issue by thomast74** [ionic-team/capacitor-plugins#1080]
### Plugin(s)
"@capacitor/local-notifications": "1.1.0"

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/core: 3.5.1
  @capacitor/cli: 3.5.1
  @capacitor/ios: 3.5.1
  @capacitor/android: 3.5.1```

### Platform(s)
Android (with target build 12)



### Current Behavior
If you schedule a notification with schedule at a specific date and the user has the setting for Alarms & reminders turned off the application crashes at the time the notification is scheduled.

Caused by java.lang.SecurityException: Caller com.aaa.android.discounts needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:395)
       at android.app.AlarmManager.setImpl(AlarmManager.java:976)
       at android.app.AlarmManager.setImpl(AlarmManager.java:936)
       at android.app.AlarmManager.setExact(AlarmManager.java:734)
       at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.triggerScheduledNotification(LocalNotificationManager.java:354)
       at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.buildNotification(LocalNotificationManager.java:242)
       at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.schedule(LocalNotificationManager.java:150)
       at com.capacitorjs.plugins.localnotifications.LocalNotificationRestoreReceiver.onReceive(LocalNotificationRestoreReceiver.java:56)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4761)
       at android.app.ActivityThread.access$1800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)


### Expected Behavior
Application should not crash and should handle this situation gracefully.



### Code Reproduction
Use any application that uses Local Notification with a schedule at date with this Alarms & Reminders turned off and it must be an Android 12 build.



### Other Technical Details
https://proandroiddev.com/quick-guide-of-alarms-on-android-12-3a864ea81910


### Additional Context

**Comment by jcesarmobile** [comment]
This is handled un the 4.0.0 beta release of the okugin
