### ISSUE TITLE
Filesystem.writeFile throws Maximum call stack size exceeded error for larger files

### ISSUE THREAD

**Issue by beonde** [ionic-team/capacitor-plugins#1138]
### Plugin(s)
@capacitor/filesystem@4.0.1

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
```

### Platform(s)

Web

### Current Behavior

When attempting to write larger images using the Filesystem.writeFile method, the RegEx.test method used in the isBase64String method throws a maximum call stack exceeded error. I have verified that the base64 string provided is valid. The size of the source image is 3.3 MB.

### Expected Behavior

For the valid base64 string to be recognized and saved to browser storage, regardless of size.

### Code Reproduction

Let me know if you need this.

### Other Technical Details

VSCode 1.70.1 on MacOS 11.6.6
Angular 13.3.1 project with Ionic 6.1.15

I haven't added iOS or Android capacitor projects yet. First testing on web and pwa only.

### Additional Context

Relax regex validation of base64 string or eliminate the test completely as in previous builds of the plugin.

```
ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.test (<anonymous>)
    at f.isBase64String (6364.5d7cc5eddf0b3c52.js:1:8220)
    at 6364.5d7cc5eddf0b3c52.js:1:2620
    at Generator.next (<anonymous>)
    at a (main.8e826124c31ed1a7.js:1:1524153)
    at R (main.8e826124c31ed1a7.js:1:1524357)
    at v.invoke (polyfills.b44f3bbb9dc50cef.js:1:7684)
    at Object.onInvoke (main.8e826124c31ed1a7.js:1:1358319)
    at v.invoke (polyfills.b44f3bbb9dc50cef.js:1:7624)
    at X (polyfills.b44f3bbb9dc50cef.js:1:17753)
    at polyfills.b44f3bbb9dc50cef.js:1:18612
    at v.invokeTask (polyfills.b44f3bbb9dc50cef.js:1:8368)
    at Object.onInvokeTask (main.8e826124c31ed1a7.js:1:1358134)
    at v.invokeTask (polyfills.b44f3bbb9dc50cef.js:1:8289)
    at v.runTask (polyfills.b44f3bbb9dc50cef.js:1:3427)
    at A (polyfills.b44f3bbb9dc50cef.js:1:10754)
    at v.invokeTask [as invoke] (polyfills.b44f3bbb9dc50cef.js:1:9531)
    at m (polyfills.b44f3bbb9dc50cef.js:1:23055)
    at C (polyfills.b44f3bbb9dc50cef.js:1:23328)
zs @ main.8e826124c31ed1a7.js:1
handleError @ main.8e826124c31ed1a7.js:1
next @ main.8e826124c31ed1a7.js:1
__tryOrUnsub @ main.8e826124c31ed1a7.js:1
next @ main.8e826124c31ed1a7.js:1
_next @ main.8e826124c31ed1a7.js:1
next @ main.8e826124c31ed1a7.js:1
next @ main.8e826124c31ed1a7.js:1
emit @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
v.run @ polyfills.b44f3bbb9dc50cef.js:1
runOutsideAngular @ main.8e826124c31ed1a7.js:1
onHandleError @ main.8e826124c31ed1a7.js:1
v.handleError @ polyfills.b44f3bbb9dc50cef.js:1
v.runGuarded @ polyfills.b44f3bbb9dc50cef.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
t.microtaskDrainDone @ polyfills.b44f3bbb9dc50cef.js:1
A @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
m @ polyfills.b44f3bbb9dc50cef.js:1
C @ polyfills.b44f3bbb9dc50cef.js:1
D @ polyfills.b44f3bbb9dc50cef.js:1
IndexedDB (async)
(anonymous) @ 6364.5d7cc5eddf0b3c52.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ 6364.5d7cc5eddf0b3c52.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
onInvoke @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
v.run @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
onInvokeTask @ main.8e826124c31ed1a7.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
v.runTask @ polyfills.b44f3bbb9dc50cef.js:1
A @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
m @ polyfills.b44f3bbb9dc50cef.js:1
C @ polyfills.b44f3bbb9dc50cef.js:1
D @ polyfills.b44f3bbb9dc50cef.js:1
IndexedDB (async)
(anonymous) @ 6364.5d7cc5eddf0b3c52.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ 6364.5d7cc5eddf0b3c52.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
onInvoke @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
v.run @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
onInvokeTask @ main.8e826124c31ed1a7.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
v.runTask @ polyfills.b44f3bbb9dc50cef.js:1
A @ polyfills.b44f3bbb9dc50cef.js:1
Promise.then (async)
V @ polyfills.b44f3bbb9dc50cef.js:1
J @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
onScheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleMicroTask @ polyfills.b44f3bbb9dc50cef.js:1
Q @ polyfills.b44f3bbb9dc50cef.js:1
X @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
z.onload @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
onInvoke @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
v.runGuarded @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
load (async)
set @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
oe @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
a @ main.8e826124c31ed1a7.js:1
R @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
onInvoke @ main.8e826124c31ed1a7.js:1
v.invoke @ polyfills.b44f3bbb9dc50cef.js:1
v.run @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
onInvokeTask @ main.8e826124c31ed1a7.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
v.runTask @ polyfills.b44f3bbb9dc50cef.js:1
A @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
m @ polyfills.b44f3bbb9dc50cef.js:1
C @ polyfills.b44f3bbb9dc50cef.js:1
D @ polyfills.b44f3bbb9dc50cef.js:1
XMLHttpRequest.send (async)
(anonymous) @ VM6:1
A @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
onScheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleTask @ polyfills.b44f3bbb9dc50cef.js:1
v.scheduleMacroTask @ polyfills.b44f3bbb9dc50cef.js:1
Ye @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ polyfills.b44f3bbb9dc50cef.js:1
n.<computed> @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
dt.exports @ main.8e826124c31ed1a7.js:1
dt.exports @ main.8e826124c31ed1a7.js:1
R.request @ main.8e826124c31ed1a7.js:1
R.<computed> @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
a @ main.8e826124c31ed1a7.js:1
R @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
getCdnImage @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
a @ main.8e826124c31ed1a7.js:1
R @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
l @ polyfills.b44f3bbb9dc50cef.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
displayMarkerJS @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
Jm @ main.8e826124c31ed1a7.js:1
A @ main.8e826124c31ed1a7.js:1
(anonymous) @ main.8e826124c31ed1a7.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
onInvokeTask @ main.8e826124c31ed1a7.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
v.runTask @ polyfills.b44f3bbb9dc50cef.js:1
v.invokeTask @ polyfills.b44f3bbb9dc50cef.js:1
m @ polyfills.b44f3bbb9dc50cef.js:1
C @ polyfills.b44f3bbb9dc50cef.js:1
D @ polyfills.b44f3bbb9dc50cef.js:1
Show 43 more frames
```

**Comment by YangFan17** [comment]
the same problem

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by beonde** [comment]
In the app below, just click the Reproduce Error in Console button in the UI.

[Minimal Sample Application with Error](https://github.com/beonde/cap-fs-bug) @jcesarmobile

**Comment by imnotakopp** [comment]
A temporary fix would be to set the encoding e.g. `encoding: Encoding.UTF_8` in your write options. This would bypass the base64 regex check and work in your case since you are writing a base64 encoded string.
