### ISSUE TITLE
(Android) Problems with splashscreen when minimizing app before hiding splashscreen

### ISSUE THREAD

**Issue by koen20** [ionic-team/capacitor-plugins#1161]
### Plugin(s)

@capcitor/splash-screen: 4.0.1

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0

[success] Android looking great! ?
```

### Platform(s)

Android

### Current Behavior

During startup Splashscreen.show is executed without autohide. After 4 seconds the splashscreen is hidden by calling SplashScreen.hide(). If you minimize the app before the splashscreen is hidden it is not possible to hide the splashscreen anymore or the app crashes.

I tested this on Android 12 and Android 6.0.1.
On Android 6.0.1 when I minimize the app during startup and then reopen it, it is no longer possible to hide the splashscreen without force closing the app.
On Android 12 the app crashes when I reopen it after minimizing during startup.

### Expected Behavior

The splashscreen should be hidden and the app should not crash.

### Code Reproduction

https://github.com/koen20/cap-splashscreen

### Additional Context

Logs when reopening app on Android 12:
```
    java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference
        at android.view.SurfaceControl.access$2600(SurfaceControl.java:89)
        at android.view.SurfaceControl$Transaction.checkPreconditions(SurfaceControl.java:2692)
        at android.view.SurfaceControl$Transaction.hide(SurfaceControl.java:2840)
        at android.app.ActivityThread.syncTransferSplashscreenViewTransaction(ActivityThread.java:4171)
        at android.app.ActivityThread.access$4500(ActivityThread.java:256)
        at android.app.ActivityThread$1.onDraw(ActivityThread.java:4148)
        at android.view.ViewTreeObserver.dispatchOnDraw(ViewTreeObserver.java:1132)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4456)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4245)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by jcesarmobile** [comment]
I can't reproduce the Splash Screen not being to be hidden anymore on Android < 12.
I can reproduce the crash, but seems to be a Google bug on the Android 12 Splash Screen API. https://issuetracker.google.com/issues/233588959
Sadly it was closed because there wasn't enough information, so would be good if you could create a new one
