### ISSUE TITLE
SplashScreen.java line 224 – Application crash at the first 2 sec

### ISSUE THREAD

**Issue by denisogolubev** [ionic-team/capacitor-plugins#1181]
### Plugin(s)
[@capacitor/splash-screen](https://capacitorjs.com/docs/apis/splash-screen)

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/ios: 4.2.0

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/ios: 4.2.0
  @capacitor/android: 4.2.0

```

### Platform(s)
Android

### Current Behavior
After updating the plugin to version 4.0.1, Firebase Crashlytics started to catch the app crash errors.

SplashScreen.java line 224
This issue has 990 crash events affecting 266 users.

Most errors have these labels:
This crash event happened in the first second of the user's session.
This crash event happened in the first 2 seconds of the user's session.

### Expected Behavior
The application should not crash.

### Code Reproduction
Basic plugin work, no specific actions from the application.

### Other Technical Details
gradle.variables
```
ext {
    minSdkVersion = 23
    compileSdkVersion = 31
    targetSdkVersion = 31
    androidxActivityVersion = '1.4.0'
    androidxAppCompatVersion = '1.4.2'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion =  '1.8.0'
    androidxFragmentVersion = '1.4.1'
    androidxWebkitVersion = '1.4.0'
    **coreSplashScreenVersion = '1.0.0'**
    $androidxMaterialVersion =  '1.3.0'
    $androidxBrowserVersion =  '1.3.0'
    firebaseMessagingVersion =  '23.0.5'
    junitVersion =  '4.13.1'
    androidxJunitVersion =  '1.1.3'
    androidxEspressoCoreVersion =  '3.4.0'
    cordovaAndroidVersion =  '10.1.1'
    $firebaseCrashlyticsVersion = '18.2.13'
}
```

android/app/src/main/res/values/styles.xml
```
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">#FFFFFF</item>
    </style>
```

### Additional Context
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFitsSystemWindows(boolean)' on a null object reference
       at com.capacitorjs.plugins.splashscreen.SplashScreen.buildViews(SplashScreen.java:224)
       at com.capacitorjs.plugins.splashscreen.SplashScreen.show(SplashScreen.java:291)
       at com.capacitorjs.plugins.splashscreen.SplashScreen.showOnLaunch(SplashScreen.java:58)
       at com.capacitorjs.plugins.splashscreen.SplashScreenPlugin.load(SplashScreenPlugin.java:21)
       at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
       at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
       at com.getcapacitor.Bridge.registerPlugin(Bridge.java:509)
       at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:464)
       at com.getcapacitor.Bridge.<init>(Bridge.java:191)
       at com.getcapacitor.Bridge.<init>(Bridge.java:65)
       at com.getcapacitor.Bridge$Builder.create(Bridge.java:1308)
       at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
       at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by denisogolubev** [comment]
Find out that was only in 1 previous build, will watch if this will reproduce in the future.
