### ISSUE TITLE
No Activity found to handle Intent VIEW

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/capacitor-plugins#1283]
### Plugin(s)

- "@capacitor/browser": "^4.0.1"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior
Watching Firebase Crashlytics, I saw users who cannot open my intent to launch a website. Here the logs that I see on Crashlytics:

**RuntimeException**

```
Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:730)
at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(:8)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**InvocationTargetException**

```
Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Method.invoke(Method.java)
       at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:125)
       at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:721)
       at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(:8)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**ActivityNotFoundException**

```
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.google.com/... (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2071)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1717)
       at android.app.Activity.startActivityForResult(Activity.java:5252)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
       at android.app.Activity.startActivityForResult(Activity.java:5203)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
       at android.app.Activity.startActivity(Activity.java:5581)
       at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:830)
       at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:279)
       at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:376)
       at com.capacitorjs.plugins.browser.Browser.open(Browser.java:112)
       at com.capacitorjs.plugins.browser.BrowserPlugin.open(BrowserPlugin.java:51)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:125)
       at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:721)
       at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(:8)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Expected Behavior
I'm not sure. Maybe a Promise rejected so we can know that the Intent could not be handle to present a message to the user?

### Code Reproduction

Full code reproduction here:
https://github.com/RRGT19/Ionic-Test-Browser-Open-Method

Code used to call te plugin:
```typescript
await Browser.open({
      url: 'https://www.google.com/',
      toolbarColor: '#F0F4FF',
      presentationStyle: 'fullscreen',
    });
```

### Other Technical Details
Here the details of the users devices that experimented this issue:

Android Version:

- 8
- 8.1.0
- 9
- 10
- 11

Devices:

- Galaxy A10s
- Galaxy A20s
- Alcatel 3L
- POCO X3 Pro
- Galaxy J4+
- Huawei Y6 2018
- Galaxy Tab A7
- Galaxy S9+
- Alcatel 3

### Additional Context
Watching the code of the `open()` method [here](https://github.com/ionic-team/capacitor-plugins/blob/main/browser/android/src/main/java/com/capacitorjs/plugins/browser/Browser.java#L97), I don't see that we are checking if the device can handle the intent, for example like [this](https://stackoverflow.com/a/29994483/10977224).

**Comment by RRGT19** [comment]
There is not a specific code reproduction, it's just a normal call to the open() method. See example below:

```typescript
await Browser.open({
      url: 'https://www.google.com/',
      toolbarColor: '#F0F4FF',
      presentationStyle: 'fullscreen',
    });
```

**Comment by jcesarmobile** [comment]
Please, provide a full sample app, not just a code snippet.
