### ISSUE TITLE
@capacitor/geolocation - LocationRequest.Builder error: cannot find symbol - class Builder

### ISSUE THREAD

**Issue by rkazakov** [ionic-team/capacitor-plugins#1593]
### Plugin(s)
@capacitor/geolocation: ^5.0.0

### Capacitor Version

```
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

Installed Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

[info] Using Gemfile: RubyGems bundle installed
[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior

```
LocationRequest locationRequest = new LocationRequest.Builder(10000)
                                                                     ^
  symbol:   class Builder
  location: class LocationRequest
```

<img width="1481" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/168863/dc20d8b6-81e0-4bd6-b572-378efaec5670">

### Expected Behavior
Android APK should be built without issues.

### Code Reproduction
None

### Other Technical Details
Android Studio Flamingo | 2022.2.1 Patch 1
macOS M2 13.3.1 (a)

### Additional Context
None

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by rkazakov** [comment]
This was fixed by running
```
npx cap migrate
```

**Comment by gianlazz** [comment]
I'm also experiencing the same issue.

**Comment by gianlazz** [comment]
It looks like there were some missing changes needed particularly to the `varibles.gradle` that weren't completely applied by the cli migration to v5 of capacitor. I followed along with the documentation and made these changes by hand.

https://capacitorjs.com/docs/updating/5-0#android

I'm now able to build the app for android though I'm now encountering a new runtime error that's causing it to crash on startup.

```
FATAL EXCEPTION: pool-13-thread-4
                                                                                                    Process: tech.lazz.app, PID: 30687
                                                                                                    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~Q0vcPgrlUx0qxAUDEjDgnQ==/tech.lazz.app-StRrFnivt95jslYu3LCa1g==/base.apk)
                                                                                                    	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.requestLocationUpdates(Unknown Source:70)
                                                                                                    	at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:131)
                                                                                                    	at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
                                                                                                    	at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
                                                                                                    	at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
```
