### ISSUE TITLE
Error with the plugin to lock the screen orientation

### ISSUE THREAD

**Issue by loicparent** [ionic-team/capacitor-plugins#1624]
### Plugin(s)
"@capacitor/screen-orientation": "^5.0.0"

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3
  @capacitor/core: 5.0.3
```

### Platform(s)
Android (on some devices … not all)

### Current Behavior
When the user click on the AppIcon (to launch the app), it gets an error message (Something like: Application stops working).

This error only occurs on some devices. Especially with Android 8.0 (on Samsung Galaxy A5).

When I look through the Android Studio Console, I can see an error message:
```
Serious error executing plugin
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780)
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.os.Parcel.readException(Parcel.java:1975)
	at android.os.Parcel.readException(Parcel.java:1913)
	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6206)
	at android.app.Activity.setRequestedOrientation(Activity.java:5840)
	at com.capacitorjs.plugins.screenorientation.ScreenOrientation.lock(ScreenOrientation.java:29)
	at com.capacitorjs.plugins.screenorientation.ScreenOrientationPlugin.lock(ScreenOrientationPlugin.java:35)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780) 
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
	at android.os.Handler.handleCallback(Handler.java:789) 
	at android.os.Handler.dispatchMessage(Handler.java:98) 
	at android.os.Looper.loop(Looper.java:164) 
	at android.os.HandlerThread.run(HandlerThread.java:65) 

FATAL EXCEPTION: CapacitorPlugins
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:789)
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780)
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
	at android.os.Handler.handleCallback(Handler.java:789) 
	at android.os.Handler.dispatchMessage(Handler.java:98) 
	at android.os.Looper.loop(Looper.java:164) 
	at android.os.HandlerThread.run(HandlerThread.java:65) 
Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.os.Parcel.readException(Parcel.java:1975)
	at android.os.Parcel.readException(Parcel.java:1913)
	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6206)
	at android.app.Activity.setRequestedOrientation(Activity.java:5840)
	at com.capacitorjs.plugins.screenorientation.ScreenOrientation.lock(ScreenOrientation.java:29)
	at com.capacitorjs.plugins.screenorientation.ScreenOrientationPlugin.lock(ScreenOrientationPlugin.java:35)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780) 
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
	at android.os.Handler.handleCallback(Handler.java:789) 
	at android.os.Handler.dispatchMessage(Handler.java:98) 
	at android.os.Looper.loop(Looper.java:164) 
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Expected Behavior
The app should opens normally without any error. If the orientation plugin is not compatible, it should use a fallback to allow the user to access the app instead of locking it with only an error message.

### Code Reproduction
Just a simple install of ionic with the package @capacitor/screen-orientation and run on device with issue such as the Samsung Galaxy A5 with Android 8.0.

(If needed, I can create a blank project but this is very basic and specific to a device issue).

_Thanks for your help,
Loïc_

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by loicparent** [comment]
I actually don't arrive to reproduce the issue with a new install of Ionic/Capacitor.
So the issue must be related to the app code or the framework updates or an incompatibility with another package.

All that I am sure is that I have the issue when I use the plugin while I don't without the Capacitor plugin.
Also, It was working fine with the Cordova package but I'm looking to switch all of the Cordova plugins to Capacitor.

You maybe have any idea of what can cause this issue?

_Thanks for your help,
Loïc_

----

Here is the list of installed packages:
```

@angular-devkit/architect@0.1502.7
@angular-devkit/build-angular@15.2.7
@angular-devkit/core@15.2.7
@angular-devkit/schematics@15.2.7
@angular/animations@15.2.8
@angular/cli@15.2.7
@angular/common@15.2.8
@angular/compiler-cli@15.2.8
@angular/compiler@15.2.8
@angular/core@15.2.8
@angular/forms@15.2.8
@angular/language-service@15.2.8
@angular/localize@15.2.8
@angular/platform-browser-dynamic@15.2.8
@angular/platform-browser@15.2.8
@angular/router@15.2.8
@auth0/angular-jwt@5.1.2
@awesome-cordova-plugins/core@6.3.0
@awesome-cordova-plugins/device-orientation@6.3.0
@capacitor-community/barcode-scanner@4.0.1
@capacitor/android@5.0.3
@capacitor/app-launcher@5.0.2
@capacitor/app@5.0.2
@capacitor/camera@5.0.2
@capacitor/cli@5.0.3
@capacitor/clipboard@5.0.2
@capacitor/core@5.0.3
@capacitor/device@5.0.2
@capacitor/geolocation@5.0.2
@capacitor/haptics@5.0.2
@capacitor/ios@5.0.3
@capacitor/keyboard@5.0.2
@capacitor/network@5.0.2
@capacitor/screen-orientation@5.0.2
@capacitor/splash-screen@5.0.2
@capacitor/status-bar@5.0.2
@hugotomazi/capacitor-navigation-bar@2.0.1
@ionic/angular-toolkit@9.0.0
@ionic/angular@7.0.4
@ionic/lab@3.2.15
@ionic/storage@2.3.1
@ngrx/effects@9.2.1
@ngrx/store-devtools@9.2.1
@ngrx/store@9.2.1
@ngx-translate/core@11.0.1
@ngx-translate/http-loader@4.0.0
@types/jasmine@3.6.11
@types/jasminewd2@2.0.10
@types/jquery@3.5.16
@types/node@18.16.2
capacitor-native-settings@5.0.0
cordova-android@11.0.0
cordova-ios@6.3.0
cordova-plugin-device-orientation@2.0.1
cordova-plugin-ios-disableshaketoedit@1.0.0
cordova-res@0.15.4
core-js@2.6.12
date-fns@2.29.3
es6-promise-plugin@4.2.2
geolib@3.3.3
gsap@3.11.5
jasmine-core@3.6.0
jasmine-spec-reporter@5.0.2
jquery@3.6.4
js-marker-clusterer@1.0.0
karma-chrome-launcher@3.2.0
karma-coverage-istanbul-reporter@3.0.3
karma-jasmine-html-reporter@1.7.0
karma-jasmine@5.1.0
karma@6.4.2
lodash@4.17.21
mapbox-gl@2.14.1
ngx-image-cropper@6.3.3
protractor@7.0.0
rxjs@7.8.1
swiper@7.4.1
ts-node@7.0.1
tslib@2.5.0
tslint@6.1.3
typescript@4.9.5
zone.js@0.13.0
```

**Comment by jcesarmobile** [comment]
Sorry, we can't proceed without a valid reproduction.
All I could find about the error is that it's Android 8 specific and can happen if your activity is transparent. So try looking for plugins that could be handling transparency of the activity or views, and if you can then reproduce, create a new issue.
