### ISSUE TITLE
[google-maps]: strokeColor is required on Android

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/capacitor-plugins#1725]
### Plugin(s)
`google-maps@5.3.0`

### Platform(s)
Android

### Current Behavior
When drawing a polyline, the map throws an error on Android with:

```
main.52e9d7a35c851942.js:1 Error: Uncaught (in promise): Error: Unhandled Error: No value for strokeColor.
Error: Unhandled Error: No value for strokeColor.
    at returnResult (VM3:770:32)
    at win.androidBridge.onmessage (VM3:745:21)
    at te (polyfills.57895b56d757dc92.js:1:18910)
    at polyfills.57895b56d757dc92.js:1:17986
    at polyfills.57895b56d757dc92.js:1:18092
    at d (main.52e9d7a35c851942.js:1:1136027)
    at te (main.52e9d7a35c851942.js:1:1136237)
    at _.invoke (polyfills.57895b56d757dc92.js:1:8747)
    at Object.onInvoke (main.52e9d7a35c851942.js:1:906705)
    at _.invoke (polyfills.57895b56d757dc92.js:1:8686)
    at _.run (polyfills.57895b56d757dc92.js:1:3778)
    at polyfills.57895b56d757dc92.js:1:19705
    at _.invokeTask (polyfills.57895b56d757dc92.js:1:9432)
    at Object.onInvokeTask (main.52e9d7a35c851942.js:1:906521)
    at _.invokeTask (polyfills.57895b56d757dc92.js:1:9353)
    at _.runTask (polyfills.57895b56d757dc92.js:1:4447)
    at U (polyfills.57895b56d757dc92.js:1:11834)
```

### Expected Behavior
Polyline can be drawn without specifying the color or  `interface Polyline extends google.maps.PolylineOptions` should have set strokeColor as required and not optional.

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ngmiduc** [comment]
### Reproduction:
[issue-google-maps-polyline.zip](https://github.com/ionic-team/capacitor-plugins/files/12426211/issue-google-maps-polyline.zip)


### Steps:
1. install npm packages and ionic/cli
2. add google maps key to `src/app/home/home.page.ts::19` and to `android/app/src/main/AndroidManifest.xml::com.google.android.geo.API_KEY`
3. run `ionic capacitor build android`
4. build android gradle to an emulator device
5. run app
6. check logs in google chrome `chrome://inspect`

### Error:
<img width="444" alt="Screenshot 2023-08-24 at 13 36 20" src="https://github.com/ionic-team/capacitor-plugins/assets/22853830/090c0388-d0c9-46b5-8b91-90850fa6b5ce">
