### ISSUE TITLE
Filesystem.readFile : I cannot read any file except the ones I create with my app, how to fix that?

### ISSUE THREAD

**Issue by TAYBI** [ionic-team/capacitor-plugins#1838]
I cannot read any file except the ones I create with my app, how to fix that?

``` js
FilePicker.pickFiles({
  multiple: false,
}).then(async (result) => {
 
  const contents = await Filesystem.readFile({
    path: result.files[0].name,
    directory: Directory.Documents,
    encoding: Encoding.UTF8,
  });
```

I am not able to get any content. it always displays the following error when selecting a file, except for the files created by the application

```
ERROR Error: Uncaught (in promise): Error: File does not exist
Error: File does not exist
    at returnResult (VM3:772:32)
    at win.androidBridge.onmessage (VM3:747:21)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:26262:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25948:55
   ```

**Comment by jcesarmobile** [comment]
It's an Android limitation, it's documented in the plugin docs that starting in Android 11, they allow to write your own files to documents folder, but don't allow to access other app files.

https://capacitorjs.com/docs/apis/filesystem#android

The only way of reading files from there would be to use a file picker plugin where the user manually picks the file, you can't access them programmatically anymore.

**Comment by TAYBI** [comment]
I am using FilePicker.pickFiles, I want to get the contents of the file after the user selects one

`result.files[0].blob` appears to be undefined

**Comment by jcesarmobile** [comment]
I'm not familiar with that plugin, but it should provide you the file content already, you should not use Filesystem plugin to read it.
Also if you are passing a file path you should not pass a directory.
