### ISSUE TITLE
@capacitor/geolocation : RuntimeException - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by neogenz** [ionic-team/capacitor-plugins#1942]
### Plugin(s)
- Capacitor Geolocation Plugin 4.0.1

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3
```

### Platform(s)

- Android (v8 to 14)

### Current Behavior

When the application, which uses the Capacitor Geolocation plugin, is put into the background for a few minutes and then brought back to the foreground, the app crashes with a `java.util.ConcurrentModificationException`. This exception occurs in the `GeolocationPlugin.handleOnResume` method, as detailed in the stack trace provided.
```
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
    at com.capacitorjs.plugins.geolocation.GeolocationPlugin.handleOnResume(GeolocationPlugin.java:49)
    at com.getcapacitor.Bridge.onResume(Bridge.java:1254)
    at com.getcapacitor.BridgeActivity.onResume(BridgeActivity.java:86)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
    at android.app.Activity.performResume(Activity.java:7490)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4256)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4328)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
java.lang.RuntimeException: Unable to resume activity {ch.tpg.boldor/ch.tpg.boldor.MainActivity}: java.util.ConcurrentModificationException
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4288)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4328)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
Exemple of scenario, it is always more or less same 
<img width="1145" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/4728161/3336ebc3-eccd-4035-a036-fdbc1e388fa5">

### Expected Behavior

The expected behavior is that the app should resume normally from the background without any crash or exception related to the Geolocation plugin.

### Additional Context

This issue seems to occur due to modifications in the `HashMap` within the `GeolocationPlugin` while iterating over it. This problem surfaces specifically when handling the `onResume` lifecycle event in Android. Here's the stack trace for reference:

**Comment by jcesarmobile** [comment]
Capacitor 4 is out of support, if you update to Capacitor 5 and geolocation plugin v5.x and the issue persists, please, create a new issue and provide a sample app that reproduces the issue.
