### ISSUE TITLE
bug(@capacitor/share): FATAL EXCEPTION java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tvoydnevnik/com.tvoydnevnik.MainActivity}: java.lang.SecurityException: com.tvoydnevnik: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by YadrovSergey** [ionic-team/capacitor-plugins#2057]
### Plugin(s)
"@capacitor/share": "^5.0.7"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.2
  @capacitor/core: 5.7.2
  @capacitor/android: 5.7.2
  @capacitor/ios: 5.7.2

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)
Android 14

minSdkVersion = 26
targetSdkVersion = 34
compileSdkVersion = 34

### Current Behavior

App crash when startup on Android 14 platform with plugin @capacitor/share
If plugin remove than app start normal.

### Expected Behavior

App should run

### Code Reproduction

when gradle:8.1.1 and install plugin @capacitor/share

### Additional Context

 E  FATAL EXCEPTION: main
                                                                                                    Process: com.tvoydnevnik, PID: 27286
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tvoydnevnik/com.tvoydnevnik.MainActivity}: java.lang.SecurityException: com.tvoydnevnik: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3823)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2484)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8227)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:573)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: java.lang.SecurityException: com.tvoydnevnik: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5718)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.capacitorjs.plugins.share.SharePlugin.load(SharePlugin.java:44)
                                                                                                    	at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
                                                                                                    	at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
                                                                                                    	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
                                                                                                    	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:661)
                                                                                                    	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:617)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Bridge.java:215)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1536)
                                                                                                    	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
                                                                                                    	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3805)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2484) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8227) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:573) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14111)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2586)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2771)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by jcesarmobile** [comment]
Using targetSdkVersion 34 is not supported in Capacitor 5, you have to keep using 33 or move to Capacitor 6, which is in RC stage at the moment.
