### ISSUE TITLE
Camera plugin 6.0 pickImages limit ignored on Android 13+

### ISSUE THREAD

**Issue by mertyldrr** [ionic-team/capacitor-plugins#2119]
### Plugin(s)

`@capacitor/camera
`
### Capacitor Version

```
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0
```

### Platform(s)

Android 13+

### Current Behavior

When calling `pickImages()` limit parameter is ignored on Android 13+. 

### Expected Behavior

Should consider provided limit

### Code Reproduction

```
    const result: GalleryPhotos = await Camera.pickImages({
      limit: 1,
      presentationStyle: 'popover',
      quality: 85,
      width: 1394,
      height: 1859
    });
```

**Comment by Ionitron** [comment]
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by LuisWolf-Snapaddy** [comment]
I also checked the behavior [here in the camera plugin](https://github.com/ionic-team/capacitor-plugins/blob/acd334dae7fc7545446cafc8fbb469200f7831f8/camera/android/src/main/java/com/capacitorjs/plugins/camera/CameraPlugin.java#L339-L343) and currently the limit is ignored if it's set to `1`. Setting it to `2` or greater works fine.

Talking to @mertyldrr it seems to crash when this logic is adjusted to `>= 1` because [`PickMultipleVisualMedia`](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickMultipleVisualMedia) needs the limit to be set to greater than one. I think the best case would be to use [`PickVisualMedia`](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia) specifically if the limit is set to `1`.

**Comment by ryaa** [comment]
The problem is that PickMultipleVisualMedia do not support maxItems = 1 and the app will crash with the below error, if 1 is provided as the argument to `ActivityResultContracts.PickMultipleVisualMedia` constructor

```
Caused by: java.lang.IllegalArgumentException: Max items must be higher than 1
                                                                                                    	at androidx.activity.result.contract.ActivityResultContracts$PickMultipleVisualMedia.<init>(ActivityResultContracts.kt:879)
                                                                                                    	at com.capacitorjs.plugins.camera.CameraPlugin.getContractForCall(CameraPlugin.java:340)
                                                                                                    	at com.capacitorjs.plugins.camera.CameraPlugin.openPhotos(CameraPlugin.java:351)
                                                                                                    	at com.capacitorjs.plugins.camera.CameraPlugin.pickImages(CameraPlugin.java:137)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:816) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$FNYM7cvgeBk0k8YXQH7M96Mrf-c(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

I think that this should be at least reflected in the camera plugin documentation for the limit option of GalleryImageOptions section (see https://capacitorjs.com/docs/apis/camera#galleryimageoptions) or the required fix applied to the camera plugin as @LuisWolf-Snapaddy suggests.
Please also see **4. PickMultipleVisualMedia do not support maxItems = 1** section [here](https://medium.com/@john6.lq/some-issues-when-using-the-photopicker-with-pickvisualmediarequest-a37f3ca02344)

**Comment by eric-horodyski** [comment]
This thread has been inactive for some time, and we’re cleaning up older items to keep the backlog focused and manageable.

Details on the effort:
[https://ionic.io/blog/keeping-capacitors-backlog-healthy](https://ionic.io/blog/keeping-capacitors-backlog-healthy)

If this is still relevant today, feel free to open a new issue with current information and we’ll review it.
