### ISSUE TITLE
Geolocation.requestPermissions() crashes the app on release build

### ISSUE THREAD

**Issue by markhermano** [ionic-team/capacitor-plugins#2198]
### Plugin(s)
@capacitor/geolocation: "^6.0.1"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1
  @capacitor/core: 6.1.2
```

### Platform(s)

- Android

### Current Behavior

- App crashes when requesting permission to access location on the non-debuggable version (release variant)
- It works okay if I'm just debugging in Android Studio
- Below is the error I get after the app crashes

```
 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.getcapacitor.b.run(Unknown Source:34)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.getcapacitor.y.a(Unknown Source:25)
    at com.getcapacitor.b.run(Unknown Source:11)
    at android.os.Handler.handleCallback(Handler.java:942) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loopOnce(Looper.java:211) 
    at android.os.Looper.loop(Looper.java:300) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
Caused by: java.lang.NullPointerException
    at com.getcapacitor.v.requestPermissions(Unknown Source:9)
    at com.capacitorjs.plugins.geolocation.GeolocationPlugin.requestPermissions(Unknown Source:12)
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.getcapacitor.y.a(Unknown Source:25) 
    at com.getcapacitor.b.run(Unknown Source:11) 
    at android.os.Handler.handleCallback(Handler.java:942) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loopOnce(Looper.java:211) 
    at android.os.Looper.loop(Looper.java:300) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Expected Behavior

- It should normally show the request permission prompt so users can allow or deny

### Code Reproduction

No custom code just a simple vue 3 code below

```ts
<script setup lang="ts">
import { Geolocation } from '@capacitor/geolocation'

const permission = async() => {
  await Geolocation.requestPermissions()
}
</script>
```

### Other Technical Details

- Tested using my Xiaomi Redmi Note 10 Pro (android 13)

**Comment by markhermano** [comment]
I managed to resolve the issue.
