### ISSUE TITLE
File System Plugin not working on above Android 29 EAccess Error

### ISSUE THREAD

**Issue by izeryab** [ionic-team/capacitor-plugins#457]
### Plugin(s)

File System Plugin

### Capacitor Version
Capacitor version 3.0.0

```
PASTE OUTPUT HERE
```
/Capacitor/Plugin: File does not exist
    java.io.FileNotFoundException: /storage/emulated/0/Documents/secrets/text.txt: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at com.capacitorjs.plugins.filesystem.Filesystem.getInputStream(Filesystem.java:152)
        at com.capacitorjs.plugins.filesystem.Filesystem.readFile(Filesystem.java:24)
        at com.capacitorjs.plugins.filesystem.FilesystemPlugin.readFile(FilesystemPlugin.java:62)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:239)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8062)
        at libcore.io.IoBridge.open(IoBridge.java:478)
### Platform(s)
Android 

### Current Behavior
File system cannot create a file 
Here is my approach to create a file
 
Check if directory secret exits
if not then create a directory
create file test.txt inside the directory `secret`

Directory exist but unable to create a file EAccess error

### Expected Behavior
If directory doesm't exist create a directory first then create a file and write data.

### Code Reproduction
Create a new capacitor add
Install file system plugin
Code to write a file
  async writeFile() {
       
        try {
            const result = await capacitorFilesystem.Filesystem.writeFile({
                path: 'secrets/text.txt',
                data: JSON.stringify(form),
                directory:capacitorFilesystem.Directory.Documents,
                encoding:  capacitorFilesystem.Encoding.UTF8
            })
            console.log('Wrote file', result);
        } catch (e) {
            console.log('Unable to write file', e);
        }
      }
Select Android Api above 29 and build
Test file write

### Other Technical Details
On android api 29 above code is working perfectly but not working on above 29
Solutions i have tried
1. Add write permissions 
2.  Add  android:requestLegacyExternalStorage="true" 
     

### Additional Context
This issue is something related to scoped storage.
Legacy External Storage cannot be used any more

**Comment by dtarnawsky** [comment]
A similar challenge exists in the Camera plugin when reading photos (CameraSource.Photos) with Android 10 and 11. A workaround is to add android:requestLegacyExternalStorage="true" to the AndroidManifest.xml. Handling scoped storage and permission would help: [https://developer.android.com/training/data-storage/use-cases](https://developer.android.com/training/data-storage/use-cases)
