### ISSUE TITLE
Network -> ios build breaks

### ISSUE THREAD

**Issue by qpre** [ionic-team/capacitor-plugins#498]
### Plugin(s)
`@capacitor/network` : `1.0.2`

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/ios: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/core: 3.0.2
```

### Platform(s)

ios

### Current Behavior

after installing `@capacitor/network`, `npx cap sync android` works, but `npx cap sync ios` fails with a compilation error (see below).

### Expected Behavior

The plugin should install on ios as it does on android

### Code Reproduction

This can be reproduced via this [repo](https://github.com/qpre/capacitor-3-plugin-network-ios-build-issue)

install dependencies then run `npx cap sync ios`.

### Additional Context

The stack trace:

```
✔ Copying web assets from build to ios/App/App/public in 186.13ms
✔ Creating capacitor.config.json in ios/App/App in 2.14ms
✔ copy ios in 215.22ms
✔ Updating iOS plugins in 9.35ms
[info] Found 4 Capacitor plugins for ios:
       @capacitor/app@1.0.2
       @capacitor/device@1.0.2
       @capacitor/network@1.0.2
       @capacitor/storage@1.0.2
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        
        ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        
        ### Command
        
        ```
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod install
        ```
        
        ### Report
        
        * What did you do?
        
        * What did you expect to happen?
        
        * What happened instead?
        
        
        ### Stack
        
        ```
        CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
        RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
        Xcode : 12.5 (12E262)
        Git : git version 2.30.1 (Apple Git-130)
        Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
        Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @
        624e5c615269ac78f1cb0b837c9fc195d5477535
        
        trunk - CDN - https://cdn.cocoapods.org/
        ```
        
        ### Plugins
        
        ```
        cocoapods-deintegrate : 1.0.4
        cocoapods-plugins     : 1.0.0
        cocoapods-search      : 1.0.0
        cocoapods-trunk       : 1.5.0
        cocoapods-try         : 1.2.0
        ```
        
        ### Podfile
        
        ```ruby
        platform :ios, '12.0'
        use_frameworks!
        
        # workaround to avoid Xcode caching of Pods that requires
        # Product -> Clean Build Folder after new Cordova plugins installed
        # Requires CocoaPods 1.6 or newer
        install! 'cocoapods', :disable_input_output_paths => true
        
        def capacitor_pods
        pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
        pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
        pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
        pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
        pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
        pod 'CapacitorStorage', :path => '../../node_modules/@capacitor/storage'
        end
        
        target 'App' do
        capacitor_pods
        # Add your Pods here
        end
        ```
        
        ### Error
        
        ```
        RuntimeError - Compilation error generating constants :
        In file included from
        /var/folders/q5/2m3ysphx02g0vkpqttjr8z8r0000gn/T/.const_generator20210624-61053-1i2zs8l:1:
        In file included from /usr/local/include/stdio.h:64:
        /usr/local/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        unsigned char   *_base;
        ^
        /usr/local/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
        unsigned char   *_base;
        ^
        _Nullable
        /usr/local/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should never be
        null
        unsigned char   *_base;
        ^
        _Nonnull
        /usr/local/include/_stdio.h:138:32: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int     (* _Nullable _read) (void *, char *, int);
        ^
        /usr/local/include/_stdio.h:138:32: note: insert '_Nullable' if the pointer may be null
        int     (* _Nullable _read) (void *, char *, int);
        ^
        _Nullable
        /usr/local/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer should never be
        null
        int     (* _Nullable _read) (void *, char *, int);
        ^
        _Nonnull
        /usr/local/include/_stdio.h:138:40: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int     (* _Nullable _read) (void *, char *, int);
        ^
        /usr/local/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may be null
        int     (* _Nullable _read) (void *, char *, int);
        ^
        _Nullable
        /usr/local/include/_stdio.h:138:40: note: insert '_Nonnull' if the pointer should never be
        null
        int     (* _Nullable _read) (void *, char *, int);
        ^
        _Nonnull
        /usr/local/include/_stdio.h:139:35: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
        ^
        /usr/local/include/_stdio.h:139:35: note: insert '_Nullable' if the pointer may be null
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
        ^
        _Nullable
        /usr/local/include/_stdio.h:139:35: note: insert '_Nonnull' if the pointer should never be
        null
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
        ^
        _Nonnull
        /usr/local/include/_stdio.h:140:32: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int     (* _Nullable _write)(void *, const char *, int);
        ^
        /usr/local/include/_stdio.h:140:32: note: insert '_Nullable' if the pointer may be null
        int     (* _Nullable _write)(void *, const char *, int);
        ^
        _Nullable
        /usr/local/include/_stdio.h:140:32: note: insert '_Nonnull' if the pointer should never be
        null
        int     (* _Nullable _write)(void *, const char *, int);
        ^
        _Nonnull
        /usr/local/include/_stdio.h:140:46: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int     (* _Nullable _write)(void *, const char *, int);
        ^
        /usr/local/include/_stdio.h:140:46: note: insert '_Nullable' if the pointer may be null
        int     (* _Nullable _write)(void *, const char *, int);
        ^
        _Nullable
        /usr/local/include/_stdio.h:140:46: note: insert '_Nonnull' if the pointer should never be
        null
        int     (* _Nullable _write)(void *, const char *, int);
        ^
        _Nonnull
        /usr/local/include/_stdio.h:144:18: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
        ^
        /usr/local/include/_stdio.h:144:18: note: insert '_Nullable' if the pointer may be null
        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
        ^
        _Nullable
        /usr/local/include/_stdio.h:144:18: note: insert '_Nonnull' if the pointer should never be
        null
        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
        ^
        _Nonnull
        In file included from
        /var/folders/q5/2m3ysphx02g0vkpqttjr8z8r0000gn/T/.const_generator20210624-61053-1i2zs8l:1:
        /usr/local/include/stdio.h:67:13: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        extern FILE *__stdinp;
        ^
        /usr/local/include/stdio.h:67:13: note: insert '_Nullable' if the pointer may be null
        extern FILE *__stdinp;
        ^
        _Nullable
        /usr/local/include/stdio.h:67:13: note: insert '_Nonnull' if the pointer should never be
        null
        extern FILE *__stdinp;
        ^
        _Nonnull
        /usr/local/include/stdio.h:386:41: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int (* _Nullable)(void *, const char *, int),
        ^
        /usr/local/include/stdio.h:386:41: note: insert '_Nullable' if the pointer may be null
        int (* _Nullable)(void *, const char *, int),
        ^
        _Nullable
        /usr/local/include/stdio.h:386:41: note: insert '_Nonnull' if the pointer should never be
        null
        int (* _Nullable)(void *, const char *, int),
        ^
        _Nonnull
        /usr/local/include/stdio.h:386:55: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int (* _Nullable)(void *, const char *, int),
        ^
        /usr/local/include/stdio.h:386:55: note: insert '_Nullable' if the pointer may be null
        int (* _Nullable)(void *, const char *, int),
        ^
        _Nullable
        /usr/local/include/stdio.h:386:55: note: insert '_Nonnull' if the pointer should never be
        null
        int (* _Nullable)(void *, const char *, int),
        ^
        _Nonnull
        /usr/local/include/stdio.h:387:44: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        fpos_t (* _Nullable)(void *, fpos_t, int),
        ^
        /usr/local/include/stdio.h:387:44: note: insert '_Nullable' if the pointer may be null
        fpos_t (* _Nullable)(void *, fpos_t, int),
        ^
        _Nullable
        /usr/local/include/stdio.h:387:44: note: insert '_Nonnull' if the pointer should never be
        null
        fpos_t (* _Nullable)(void *, fpos_t, int),
        ^
        _Nonnull
        /usr/local/include/stdio.h:388:41: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        int (* _Nullable)(void *));
        ^
        /usr/local/include/stdio.h:388:41: note: insert '_Nullable' if the pointer may be null
        int (* _Nullable)(void *));
        ^
        _Nullable
        /usr/local/include/stdio.h:388:41: note: insert '_Nonnull' if the pointer should never be
        null
        int (* _Nullable)(void *));
        ^
        _Nonnull
        /usr/local/include/stdio.h:384:6: error: pointer is missing a nullability type specifier
        (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        FILE    *funopen(const void *,
        ^
        /usr/local/include/stdio.h:384:6: note: insert '_Nullable' if the pointer may be null
        FILE    *funopen(const void *,
        ^
        _Nullable
        /usr/local/include/stdio.h:384:6: note: insert '_Nonnull' if the pointer should never be
        null
        FILE    *funopen(const void *,
        ^
        _Nonnull
        13 errors generated.
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:131:in
        `block in calculate'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in
        `open'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:110:in
        `calculate'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:49:in
        `initialize'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `new'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in
        `<module:Libc>'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:7:in
        `<module:Ethon>'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:2:in `<top
        (required)>'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon.rb:16:in `<top
        (required)>'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top
        (required)>'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in
        `download_typhoeus_impl_async'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in
        `download_and_save_with_retries_async'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in
        `download_file_async'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in
        `download_file'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:284:in
        `ensure_versions_file_loaded'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:208:in
        `search'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in
        `block in search'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in
        `select'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in
        `search'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in
        `create_set_from_sources'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in
        `find_cached_set'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in
        `specifications_for_dependency'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in
        `search_for'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in
        `block in sort_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in
        `each'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in
        `sort_by'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in
        `sort_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in
        `block in sort_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in
        `with_no_such_dependency_error_handling'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in
        `sort_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in
        `push_state_for_requirements'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in
        `require_nested_dependencies_for'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in
        `activate_new_spec'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in
        `attempt_to_activate'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in
        `process_topmost_state'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in
        `resolve'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in
        `resolve'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in
        `resolve'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in
        `block in resolve_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in
        `section'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in
        `resolve_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in
        `analyze'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in
        `analyze'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in
        `block in resolve_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in
        `section'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in
        `resolve_dependencies'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in
        `install!'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in
        `run'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in
        `run'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in
        `run'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top
        (required)>'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `load'
        /usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `<main>'
        ```
        
        ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by jcesarmobile** [comment]
That error is not from Capacitor but from CocoaPods.
Are you on an Apple Silicon M1 Mac?
There are a few problems with them and CocoaPods
https://github.com/ionic-team/capacitor/discussions/4475
https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1/64901980#64901980

**Comment by qpre** [comment]
Hello @jcesarmobile and thank you for your answer !

I'm on an Intel MacBook Pro from 2019, `sudo gem install ffi` does not fix it for me and `pod install` works in non-capacitor projects thus my refering of this on this repo.

Although: I had cocoapods installed via HomeBrew, after removing it and installing it via bundler if works !
