### ISSUE TITLE
Android app crash when open in mobile

### ISSUE THREAD

**Issue by KevinKu** [ionic-team/capacitor-plugins#570]
### Plugin(s)

    
   
   
    "@capacitor/push-notifications": "^1.0.3"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.2.0
  @capacitor/cli: 3.2.0
  @capacitor/android: 3.2.0
```

### Platform(s)

Android  ^8.0

### Current Behavior

App crash when open in mobile

### Expected Behavior

After open app in mobile , it should work , not crash.

### Code Reproduction

[crash example](https://github.com/KevinKu/crash)

#### Setup of reproduce crash

first , use the command to init project
```
npm install
```

then , build source code
```
npm run build
```

use the command to generate android studio project
```
npx cap add android
```

put google-services.json to android/app/ 

then,open android directory with android studio.

run app in adroid emulator. (should be over 8.0)

the error log in Logcat.

### Other Technical Details

Android 11 Emulator Error Output

```
2021-08-30 11:26:34.346 4837-4898/crash.com.tw E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3646)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:832)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:820)
        at com.capacitorjs.plugins.pushnotifications.NotificationChannelManager.createChannel(NotificationChannelManager.java:88)
        at com.capacitorjs.plugins.pushnotifications.NotificationChannelManager.createChannel(NotificationChannelManager.java:50)
        at com.capacitorjs.plugins.pushnotifications.PushNotificationsPlugin.createChannel(PushNotificationsPlugin.java:178)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:37)
        at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:796)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3301)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3322)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1465)
    
    
    
    --------- beginning of crash
2021-08-30 11:26:34.347 4837-4898/crash.com.tw E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: crash.com.tw, PID: 4837
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:601)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalArgumentException
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3646)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:832)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:820)
        at com.capacitorjs.plugins.pushnotifications.NotificationChannelManager.createChannel(NotificationChannelManager.java:88)
        at com.capacitorjs.plugins.pushnotifications.NotificationChannelManager.createChannel(NotificationChannelManager.java:50)
        at com.capacitorjs.plugins.pushnotifications.PushNotificationsPlugin.createChannel(PushNotificationsPlugin.java:178)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:37)
        at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:796)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3301)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3322)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1465)
```

**Comment by KevinKu** [comment]
I add Code Reproduction section.

Thanks!

**Comment by jcesarmobile** [comment]
You are missing the name of the channel, which is a mandatory parameter.
It's not obvious in the docs because it doesn't show which params are optional and which ones are mandatory.
https://capacitorjs.com/docs/apis/push-notifications#channel

But it should be clear if you take a look into the plugin types, the ones with `?` are optional
https://github.com/ionic-team/capacitor-plugins/blob/main/push-notifications/src/definitions.ts#L305-L384

In Angular and React apps the compiler will complain if you miss mandatory params, not sure if vue can be configured somehow to do the same.

I've [reported an issue](https://github.com/ionic-team/capacitor-site/issues/367) on the docs site for adding information about optional/mandatory types.
