### ISSUE TITLE
Camera plugin error : ExifInterface got an unsupported image format file

### ISSUE THREAD

**Issue by Brizakk** [ionic-team/capacitor-plugins#711]
### Plugin(s)

Camera

### Capacitor Version

Latest Dependencies:       

  @capacitor/cli: 3.3.2    
  @capacitor/core: 3.3.2   
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2    

Installed Dependencies:    

  @capacitor/cli: 3.2.4    
  @capacitor/core: 3.3.1   
  @capacitor/android: 3.3.1
  @capacitor/ios: 3.3.1  

### Platform(s)
Android

### Current Behavior
Calling Camera.getPhoto() to take a picture on a Xiaomi Redmi 8 generate this error when I confirm the picture. I can't get the returned object photo.

`Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
java.io.IOException: Invalid byte order: ffff8950
	at android.media.ExifInterface.readByteOrder(ExifInterface.java:3128)
	at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2443)
	at android.media.ExifInterface.getMimeType(ExifInterface.java:2321)
	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1755)
	at android.media.ExifInterface.<init>(ExifInterface.java:1449)
	at com.bumptech.glide.load.resource.bitmap.n.a(SourceFile:3)
	at com.bumptech.glide.load.b.a(SourceFile:12)
	at com.bumptech.glide.load.resource.bitmap.k.a(SourceFile:22)
	at com.bumptech.glide.load.resource.bitmap.k.a(SourceFile:11)
	at com.bumptech.glide.load.resource.bitmap.t.a(SourceFile:10)
	at com.bumptech.glide.load.resource.bitmap.t.a(SourceFile:1)
	at com.bumptech.glide.load.engine.g.a(SourceFile:12)
	at com.bumptech.glide.load.engine.g.a(SourceFile:5)
	at com.bumptech.glide.load.engine.g.a(SourceFile:1)
	at com.bumptech.glide.load.engine.q.a(SourceFile:6)
	at com.bumptech.glide.load.engine.q.a(SourceFile:2)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:70)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:58)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:53)
	at com.bumptech.glide.load.engine.DecodeJob.e(SourceFile:3)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:41)
	at com.bumptech.glide.load.engine.w.a(SourceFile:19)
	at com.mi.android.globalminusscreen.glide.g.a(SourceFile:6)
	at com.bumptech.glide.load.engine.w.a(SourceFile:12)
	at com.bumptech.glide.load.engine.DecodeJob.l(SourceFile:4)
	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:4)
	at com.bumptech.glide.load.engine.DecodeJob.run(SourceFile:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	at com.bumptech.glide.load.engine.z.a$a$a.run(SourceFile:8)`

### Code Reproduction

```
async takePicture() {
    const image = await Camera.getPhoto({
      quality: 100,
      allowEditing: true,
      resultType: CameraResultType.Uri,
      preserveAspectRatio: true,
      presentationStyle: 'fullscreen',
      promptLabelHeader: 'Continue as',
      promptLabelPhoto: 'From photos',
      promptLabelPicture: 'Take a picture'
    });

    this.imageUrl = image.webPath;

    this.photos.unshift({
      data: this.imageUrl
    });
  }
```

### Other Technical Details

@capacitor/camera : "^1.1.2"
Ionic version : 6.17.0
Xiaomi Redmi 8

**Comment by jcesarmobile** [comment]
Does it happen with all images or just with a few? the message says it could be corrupted.

**Comment by Brizakk** [comment]
It happens with all images...

**Comment by Vinche59** [comment]
It looks very similar to this: https://github.com/bumptech/glide/issues/3851

**Comment by jcesarmobile** [comment]
I just tested on a RedMi Note 8 and I could use Camera plugins without problems. (not sure how different it is from RedMi 8)
Can you provide more information?
Is this for Camera images or Gallery images?
What's the Android version of your device?
In case it's for Camera images, are you using default Camera app or a different app? 
In case it's for Gallery images, which app are you using? Google Photos? Gallery? other?

**Comment by jcesarmobile** [comment]
closing due to the lack of response

**Comment by Brizakk** [comment]
Strangely on "RedMi Note" it works but not on "Redmi" models... 
Yes it is for Camera images with **10QKQ1191014.001** as Android version and i'm using default Camera app.

Sorry for the lack of response but I was on leave of absence at my work and didn't see your response.... So can you please reopen the issue ?
