### ISSUE TITLE
Unable to select gallery image on Android 12

### ISSUE THREAD

**Issue by cburnicki** [ionic-team/capacitor-plugins#722]
### Plugin(s)
@capacitor/camera@1.2.1
@capacitor/camera@1.2.0
@capacitor/camera@1.1.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 3.3.2
  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2

[success] Android looking great! 👌
```

### Platform(s)
Android 12, Google Pixel 5

### Current Behavior
Cannot select a gallery image using the 1Gallery gallery app and the camera plugin.

### Expected Behavior
Camera plugin should return an imageUrl

### Code Reproduction
[https://github.com/cburnicki/ionicgallery](https://github.com/cburnicki/ionicgallery)

### Other Technical Details
Permissions `android.permission.READ_EXTERNAL_STORAGE` and `android.permission.WRITE_EXTERNAL_STORAGE` are set.

### Additional Context

**This bug does not happen with the Google Photos app.**
It seems to work on Android devices with versions < 12.
It works on Android 12 using the camera plugin version 1.0.1.

ADB logcat output:
```
12-05 11:16:12.006  4385  4614 E MediaProvider: Permission to access file: /storage/emulated/0/DCIM/Camera/PXL_20211204_205856164.jpg is denied
12-05 11:16:12.007  5485  5485 W System.err: java.lang.reflect.InvocationTargetException
12-05 11:16:12.008  5485  5485 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 11:16:12.008  5485  5485 W System.err: 	at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:155)
12-05 11:16:12.008  5485  5485 W System.err: 	at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0$Plugin(Plugin.java:117)
12-05 11:16:12.008  5485  5485 W System.err: 	at com.getcapacitor.-$$Lambda$Plugin$9tit0PZrRMA5UA4Z_xqI4yDk4JY.onActivityResult(Unknown Source:6)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:145)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
12-05 11:16:12.008  5485  5485 W System.err: 	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1380)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.Activity.performStart(Activity.java:8113)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
12-05 11:16:12.008  5485  5485 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-05 11:16:12.009  5485  5485 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
12-05 11:16:12.009  5485  5485 W System.err: 	at android.os.Looper.loop(Looper.java:288)
12-05 11:16:12.009  5485  5485 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7838)
12-05 11:16:12.009  5485  5485 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 11:16:12.009  5485  5485 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-05 11:16:12.009  5485  5485 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-05 11:16:12.009  5485  5485 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
12-05 11:16:12.009  5485  5485 W System.err: 	at com.capacitorjs.plugins.camera.CameraPlugin.returnFileURI(CameraPlugin.java:549)
12-05 11:16:12.009  5485  5485 W System.err: 	at com.capacitorjs.plugins.camera.CameraPlugin.returnResult(CameraPlugin.java:522)
12-05 11:16:12.009  5485  5485 W System.err: 	at com.capacitorjs.plugins.camera.CameraPlugin.processPickedImage(CameraPlugin.java:361)
12-05 11:16:12.009  5485  5485 W System.err: 	at com.capacitorjs.plugins.camera.CameraPlugin.processPickedImage(CameraPlugin.java:317)
12-05 11:16:12.009  5485  5485 W System.err: 	... 27 more
12-05 11:16:12.010  5485  5485 D Capacitor/AppPlugin: Firing change: true
12-05 11:16:12.010  5485  5485 V Capacitor/AppPlugin: Notifying listeners for event appStateChange
12-05 11:16:12.010  5485  5485 D Capacitor/AppPlugin: No listeners found for event appStateChange
12-05 11:16:12.010  5485  5485 D Capacitor: App resumed
```

**Comment by jcesarmobile** [comment]
I can't reproduce on the Android 12 emulator. I don't have a real Android 12 device to test yet.

Can you provide more information about your testing environment?
Real device or emulator?
Device model?
App used to pick the pictures?

**Comment by jcesarmobile** [comment]
I just tested on a Pixel 5 with Android 12 and it also worked.
Did you use Google Photos app or a different gallery app?

**Comment by cburnicki** [comment]
Sorry, I didn't get to test it on an emulator yet. The gallery app I am using is called 1Gallery.
Tomorrow I will have time to test it with Google Photos.

**Comment by jcesarmobile** [comment]
Thanks, I can reproduce with 1Gallery app

**Comment by cburnicki** [comment]
Yes, I can confirm that it does in fact not happen with Google Photos.

**Comment by sander-spruit** [comment]
I have the same issue. It appears to be related to SDK30 requiring different permissions. Also in need of a fix!

**Comment by riderx** [comment]
Same here : https://github.com/ionic-team/capacitor/issues/2171

**Comment by mareiski** [comment]
I have the same issue when using the huawei photos app. With XGallery I can't select multiple images properly but with google photos it works as expected.

**Comment by sverdlov** [comment]
I have the same on Xiaomi Redmi Note 8 Pro. Android version 11. Plug-in returns "No image picked" for standart gallery app and for Google Photos. Checking Google Photos as 'default' resolves issue.
