### ISSUE TITLE
Share Plugin crashes when trying to share file

### ISSUE THREAD

**Issue by digaus** [ionic-team/capacitor-plugins#754]
### Plugin(s)
Share Plugin

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/core: 3.3.4
  @capacitor/cli: 3.2.3
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4
```

### Platform(s)
Android

### Current Behavior
App crashes

```
2022-01-10 19:57:29.820 25077-28638/com.home.shelly V/Capacitor: callback: 123532095, pluginId: Share, methodName: share, methodData: {"title":"Shelly Home Backup","text":"Shelly Home Backup","dialogTitle":"Shelly Home Backup","url":"file:\/\/\/data\/user\/0\/com.home.shelly\/files\/ShellyHome\/shelly-home-backup.txt"}
2022-01-10 19:57:29.823 25077-28595/com.home.shelly E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.home.shelly/files/ShellyHome/shelly-home-backup.txt
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
        at com.capacitorjs.plugins.share.SharePlugin.share(SharePlugin.java:96)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Expected Behavior

Ability to share txt file

### Code Reproduction
```
       const options: WriteFileOptions = {
            path,
            data: JSON.stringify(data),
            directory: baseDirectory,
            recursive: true,
            encoding: Encoding.UTF8,
        };
        const result: WriteFileResult = await Filesystem.writeFile(options).catch(() => null);
        if (result) {
            console.log(result)
            
            await Filesystem.readFile({
                path,
                directory: baseDirectory,
                encoding: Encoding.UTF8,
            }).then(console.log)  // -> File saved correctly
            await Share.share({
                title: 'Shelly Home Backup',
                text: 'Shelly Home Backup',
                dialogTitle: 'Shelly Home Backup',
                url: result.uri,
            });
        }


```

**Comment by digaus** [comment]
When using `Directory.External` isntead of `Directory.Data` it works for Android.

Should be mentioned in the docs.
