### ISSUE TITLE
NullPointerException when open keyboard

### ISSUE THREAD

**Issue by sverdlov** [ionic-team/capacitor-plugins#787]
### Plugin(s)
"@capacitor/keyboard": "^1.2.0"

### Capacitor Version
```
  @capacitor/cli: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/ios: 3.3.3

```

### Platform(s)
Android

### Current Behavior
I've noticed an error in Crashlytics. 

As I see, it throws after keyboard close.

### Other Technical Details
Some affected devices
ZTE 8010, Android 10
Galaxy A50, Android 11
Galaxy M21, Android 11
Galaxy A30s, Android 11

### Additional Context
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.capacitorjs.plugins.keyboard.Keyboard$KeyboardEventListener.onKeyboardEvent(java.lang.String, int)' on a null object reference
       at com.capacitorjs.plugins.keyboard.Keyboard$1.onGlobalLayout(Keyboard.java:107)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2681)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1770)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7673)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
       at android.view.Choreographer.doCallbacks(Choreographer.java:851)
       at android.view.Choreographer.doFrame(Choreographer.java:786)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:7976)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)
```

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
I can easily prevent the null pointer exception by not emitting the event if the listener is not null, but would be helpful if we could figure out why the listener is null in first place.

**Comment by sverdlov** [comment]
Hi. I can't provide a sample app. I didn't get this error on my devices. I think it's pretty rare. So far only 4 times for last week. I don't use the plugin directly. As I can see in the logs, the error pops up after the input loses focus.
