### ISSUE TITLE
PWA dynamic imports fail with vite

### ISSUE THREAD

**Issue by DinosaurDad** [ionic-team/capacitor-plugins#903]
### Plugin(s)
@ionic/pwa-elements 3.1.1
@capacitor/camera 1.3.1

### Capacitor Version
3.4.3

### Platform(s)
Browser (PWA)
Vite 2.8.6

### Current Behavior
Error when trying to use the PWA Elements camera with vite:

```
TypeError: Failed to fetch dynamically imported module:
   http://localhost:3000/node_modules/.vite/pwa-action-sheet.entry.js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isProxied')
    at core-f86805ad.js:1176:25
    at step (core-f86805ad.js:45:23)
    at Object.next (core-f86805ad.js:26:53)
    at fulfilled (core-f86805ad.js:17:58)
```

### Expected Behavior
Module should load and a modal camera should appear.

### Code Reproduction
https://github.com/DinosaurDad/capacitor-pwa-camera-vite

**Comment by DinosaurDad** [comment]
Created in wrong repository.
